export const predictionManagerAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "initialOwner", type: "address", internalType: "address" },
      { name: "_kpTokenAddress", type: "address", internalType: "address" },
      { name: "_treasuryAddress", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "MarketCreated",
    inputs: [
      { name: "marketId", type: "uint256", internalType: "uint256", indexed: true },
      { name: "creator", type: "address", internalType: "address", indexed: true },
      { name: "contentCID", type: "string", internalType: "string", indexed: false },
      { name: "category", type: "string", internalType: "string", indexed: false },
      { name: "deadline", type: "uint256", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MarketResolved",
    inputs: [
      { name: "marketId", type: "uint256", internalType: "uint256", indexed: true },
      { name: "winningOutcome", type: "uint8", internalType: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PayoutClaimed",
    inputs: [
      { name: "marketId", type: "uint256", internalType: "uint256", indexed: true },
      { name: "user", type: "address", internalType: "address", indexed: true },
      { name: "totalTransferAmount", type: "uint256", internalType: "uint256", indexed: false },
      { name: "netReward", type: "uint256", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PredictionPlaced",
    inputs: [
      { name: "marketId", type: "uint256", internalType: "uint256", indexed: true },
      { name: "user", type: "address", internalType: "address", indexed: true },
      { name: "choice", type: "uint8", internalType: "uint8", indexed: false },
      { name: "rawAmount", type: "uint256", internalType: "uint256", indexed: false },
      { name: "weightedAmount", type: "uint256", internalType: "uint256", indexed: false },
      { name: "multiplier", type: "uint256", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", internalType: "address", indexed: true },
      { name: "newOwner", type: "address", internalType: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "BASIS_POINTS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_BONUS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimWinnings",
    inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createMarket",
    inputs: [
      { name: "_contentCID", type: "string", internalType: "string" },
      { name: "_category", type: "string", internalType: "string" },
      { name: "_oracle", type: "address", internalType: "address" },
      { name: "_deadlineTimestamp", type: "uint256", internalType: "uint256" },
      { name: "_platformFeeBps", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "kpToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markets",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "oracle", type: "address", internalType: "address" },
      { name: "marketStartTimestamp", type: "uint256", internalType: "uint256" },
      { name: "deadlineTimestamp", type: "uint256", internalType: "uint256" },
      { name: "totalYesStakedRaw", type: "uint256", internalType: "uint256" },
      { name: "totalNoStakedRaw", type: "uint256", internalType: "uint256" },
      { name: "totalYesStakedWeighted", type: "uint256", internalType: "uint256" },
      { name: "totalNoStakedWeighted", type: "uint256", internalType: "uint256" },
      { name: "platformFeeBps", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum PredictionManager.Status" },
      { name: "winningOutcome", type: "uint8", internalType: "enum PredictionManager.Outcome" },
      { name: "contentCID", type: "string", internalType: "string" },
      { name: "category", type: "string", internalType: "string" },
      { name: "creator", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextMarketId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "placePrediction",
    inputs: [
      { name: "marketId", type: "uint256", internalType: "uint256" },
      { name: "_choice", type: "uint8", internalType: "enum PredictionManager.Outcome" },
      { name: "_amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveMarket",
    inputs: [
      { name: "marketId", type: "uint256", internalType: "uint256" },
      { name: "_outcome", type: "uint8", internalType: "enum PredictionManager.Outcome" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTreasuryAddress",
    inputs: [{ name: "_newTreasury", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasuryAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userStakes",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "yesAmountWeighted", type: "uint256", internalType: "uint256" },
      { name: "noAmountWeighted", type: "uint256", internalType: "uint256" },
      { name: "yesAmountRaw", type: "uint256", internalType: "uint256" },
      { name: "noAmountRaw", type: "uint256", internalType: "uint256" },
      { name: "claimed", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
] as const;

